apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palworld.fullname" . }}-ini
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
data:
  settings.conf: |
    {{- range .Values.serverConfig }}
    {{ .name }}={{ .value }}
    {{- end }}

